


var applicationData = {
categories: [
{
  name: "Ruta Principal",
  stations: [
    { /* 0 */ name: "Tanjung Priuk ", },
    { /* 1 */ name: "Enggano",  },
    { /* 2 */ name: "Permai Koja", },
    { /* 3 */ name: "Walikota Jakarta Utara", },
    { /* 4 */ name: "Karet", },
    { /* 5 */ name: "Setiabudi", },
    { /* 6 */ name: "Dukuh Atas", },
    { /* 7 */ name: "Tosari ICBC", },
    { /* 8 */ name: "Flyover Klender", },
    { /* 9 */ name: "Stasiun Klender", },
    { /* 10 */ name: "Cipinang", },
    { /* 11 */ name: "Bunderan HI",  },
    { /* 12 */ name: "Imigrasi Jakarta Timur",  },
    { /* 13 */ name: "Pasar Enjo",  },
    { /* 14 */ name: "Flyover Jatinegara", },
    { /* 15 */ name: "Stasiun Jatinegara 2", },
    { /* 16 */ name: "Jatinegara RS Premier", },
    { /* 17 */ name: "Kampung Melayu",  },
    { /* 18 */ name: "Sarinah",  },
    { /* 19 */ name: "Bank Indonesia",  },
    { /* 20 */ name: "Monumen Nasional", },
    { /* 21 */ name: "Harmoni",  },
    { /* 22 */ name: "Sawah Besar", },
    { /* 23 */ name: "Mangga Besar", },
    { /* 24 */ name: "Olimo",  },
    { /* 25 */ name: "Glodok",  },
    { /* 26 */ name: "Stasiun Kota", },
    { /* 27 */ name: "Pulogadung", },
    { /* 28 */ name: "Bermis",  },
    { /* 29 */ name: "Pulomas", },
    { /* 30 */ name: "ASMI1",  },
    { /* 31 */ name: "Pedongkelan", },
    { /* 32 */ name: "Cempaka Timur",  },
    { /* 33 */ name: "RS Islam",  },
    { /* 34 */ name: "Cempaka Tengah",  },
    { /* 35 */ name: "Pasar Cempaka Putih", },
    { /* 36 */ name: "Rawa Selatan",  },
    { /* 37 */ name: "Galur",  },
    { /* 38 */ name: "Senen",  },
    { /* 39 */ name: "Atrium", },
    { /* 40 */ name: "RSPAD",  },
    { /* 41 */ name: "DepLu",  },
    { /* 42 */ name: "Gambir 1", },
    { /* 43 */ name: "Istiqlal",  },
    { /* 44 */ name: "Juanda",  },
    { /* 45 */ name: "Pecenongan",  },
    { /* 46 */ name: "Harmoni",  },
    { /* 47 */ name: "Kalideres", },
    { /* 48 */ name: "Pesakih",  },
    { /* 49 */ name: "Sumur Bor", },
    { /* 50 */ name: "Rawa Buaya", },
    { /* 51 */ name: "Jembatan Baru", },
    { /* 52 */ name: "Dispenda Samsat Barat",  },
    { /* 53 */ name: "Jembatan Gantung",  },
    { /* 54 */ name: "Taman Kota",  },
    { /* 55 */ name: "Indosiar",  },
    { /* 56 */ name: "Jelambar",  },
    { /* 57 */ name: "Grogor",  },
    { /* 58 */ name: "Sumber Waras",  },
    { /* 59 */ name: "Kampung Melayu", },
    { /* 60 */ name: "Bidara Cina",  },
    { /* 61 */ name: "Gelanggang Remaja", },
    { /* 62 */ name: "Cawang Otista",  },
    { /* 63 */ name: "Cawang BNN",  },
    { /* 64 */ name: "Cawang UKI",  },
    { /* 65 */ name: "BKN",  },
    { /* 66 */ name: "Cililitan PGC", },
    { /* 67 */ name: "Pasar Kramat Jati",  },
    { /* 68 */ name: "Pasar Induk",  },
    { /* 69 */ name: "RS Harapan Bunda",  },
    { /* 70 */ name: "Flyover Raya Bogor", },
    { /* 71 */ name: "Tanah Merdeka",  },
    { /* 72 */ name: "Kampung Rambutan", },
    { /* 73 */ name: "Pluit",  },
    { /* 74 */ name: "Penjaringan",  },
    { /* 75 */ name: "Jembatan Tiga", },
    { /* 76 */ name: "Jembatan Dua",  },
    { /* 77 */ name: "Jembatan Besi", },
    { /* 78 */ name: "Stasiun Grogol Latumenten",  },
    { /* 79 */ name: "Grogol 2 Reformasi",  },
    { /* 80 */ name: "S Parman Podomoro City", },
    { /* 81 */ name: "RS Harapan Kita",  },
    { /* 82 */ name: "Slipi Kemanggisan", },
    { /* 83 */ name: "Slipi Petamburan",  },
    { /* 84 */ name: "Senayan JCC",  },
    { /* 85 */ name: "Semanggi",  },
    { /* 86 */ name: "Gatot Subroto LIPI",  },
    { /* 87 */ name: "Gatot Subroto Jamsostek", },
    { /* 88 */ name: "Kuningan Barat",  },
    { /* 89 */ name: "Tegal Parang",  },
    { /* 90 */ name: "Pancoran Barat", },
    { /* 91 */ name: "Pancoran Tugu",  },
    { /* 92 */ name: "Tebet BKPM",  },
    { /* 93 */ name: "Cikoko Stasiun Cawang", },
    { /* 94 */ name: "Cawang Ciliwung", },
    { /* 95 */ name: "Cawang BNN",  },
    { /* 96 */ name: "Cawang UKI",  },
    { /* 97 */ name: "Tol Jagorawi",  },
    { /* 98 */ name: "Taman Mini Garuda",  },
    { /* 99 */ name: "Pinang Ranti",  },


  ],

},
]
};
